name: deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout deploy branch
        uses: actions/checkout@v3
        with:
          ref: deploy
          path: book
      - name: Copy .git directory
        run: cp -r book/.git .git-book
      - name: Download mdBook binaries and build
        run: |
          mkdir bin
          curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.18/mdbook-v0.4.18-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=bin
          bin/mdbook build
      - name: Restore .git directory
        run: cp -r .git-book book/.git
      - name: Commit build artifacts
        run: |
          cd book
          git config user.name ${GITHUB_ACTOR}
          git config user.email ${GITHUB_ACTOR}@users.noreply.github.com
          git add .
          git commit -m "Update page"
      - name: Push and deploy
        run: |
          cd book
          REPO="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
          git push ${REPO}
